export const DescripcionSeguimiento = [
  '100% INASISTENCIA',
  'ASISTENCIA',
  'AUSENCIA CON JUSTIFICACIÓN',
  'AUSENCIA SIN JUSTIFICACIÓN',
  'CERTIFICADO MEDICO',
  'CERTIFICADO DE INTERNACIÓN',
  'CONTROL RUTINARIO',
  'CONTROL ALIMENTICIO',
  'OTRA SITUACIÓN',
  'MALA CONDUCTA',
];
