export enum ROL {
  ALUMNO,
  ADMIN,
  DIRECTOR,
  JEFETALLER,
  PRECEPTOR,
  PROFESOR,
}
export const RolConst = {
  ALUMNO: 'ALUMNO',
  ADMIN: 'ADMIN',
  DIRECTOR: 'DIRECTOR',
  JEFETALLER: 'JEFETALLER',
  PRECEPTOR: 'PRECEPTOR',
  PROFESOR: 'PROFESOR',
};
